image: msrd0/cmake-qt5:alpine

build:
  stage: build
  before_script:
    - sudo apk add --no-cache tar xz
  script:
    - pushd QtWebApp
    - mkdir build
    - pushd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    - mkdir root
    - make DESTDIR=root install
    - pushd root
    - tar cfJ ../../../qtwebapp.tar.xz --owner=root --group=root *
    - popd # root
    - popd # build
    - popd # QtWebApp
  artifacts:
    paths:
      - qtwebapp.tar.xz

demos:
  stage: test
  before_script:
    - sudo tar xfJ qtwebapp.tar.xz -C /
    - sudo ldconfig /usr/local/lib/
  script:
    - pushd Demo1
    - mkdir build
    - cd build
    - cmake ..
    - make
    - popd # Demo1
    - pushd Demo2
    - mkdir build
    - cd build
    - cmake ..
    - make
    - popd # Demo2
    - mv Demo1/build/demo1 Demo2/build/demo2 .
  artifacts:
    paths:
      - demo1
      - demo2
